spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pawsitive?characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: root
    password: Abcd123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M
